---
title: "CBoomhower_CaseStudyUnit6"
author: "Chris Boomhower"
date: "June 17, 2016"
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(downloader)
require(dplyr)
require(ggplot2)
library(knitr)
```

```{r}
##############################
## Chris Boomhower
## MSDS 6306
## Unit 6 Case Study
## 06/11/2016
##############################

## Load required packages
# require(downloader)
#require(tidyr)

## Verify current working directory
# getwd()
# setwd("Analysis//Data")
# getwd()

## Download data
prodURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv"

download(prodURL, destfile = "GrossDomesticProduct.csv")

list.files() # Confirm download to working directory

#product <- read.csv("GrossDomesticProduct.csv")
#education <- read.csv("Education.csv")
#str(product)
#str(education)

## Import Gross Domestic Product data and review raw
productRaw <- read.csv("GrossDomesticProduct.csv", stringsAsFactors = FALSE, header = FALSE) # Try reading characters in as strings instead of factors for easier manipulation
str(productRaw) # Review raw data internal structure details
head(productRaw) # Review beginning rows to ensure no blank observations
tail(productRaw, 100) # Review ending rows to ensure no blank observations

product <- productRaw[6:236,] # Remove empty rows at beginning and end of productRaw data.frame
str(product) # Review raw data internal structure details once more
head(product) # Review beginning rows once more
tail(product) # Review ending rows once more

## Check NAs in imported columns to identify empty columns
sum(!is.na(product[,c(3,7:10)])) # Detect total number of valid entries
# paste("Column 3 NAs =", sum(is.na(product$V3))) # Output NA counts for empty columns
# paste("Column 7 NAs =", sum(is.na(product$V7)))
# paste("Column 8 NAs =", sum(is.na(product$V8)))
# paste("Column 9 NAs =", sum(is.na(product$V9)))
# paste("Column 10 NAs =", sum(is.na(product$V10)))

## Check character column suspected of having empty character entries
sum(product$V6 != "") # Check character type column for valid entries
sum(product$V6 == "") # Output empty entry counts

## Extract only valid columns from raw data
product <- product[,c(1,2,4:6)]

## Provide names for each column
names(product) <- c("Country.Code","Country.Rank", "Economy", "GDP.Millions.of.US.Dollars", "Comments")
names(product) # Ensure names added correctly

## Replace comment reference with comment from original data's legend
product[product$Comments != "",] # View valid comment column entries before edits
product$Comments[product$Comments == 'a'] <- "Includes Former Spanish Sahara"
product$Comments[product$Comments == 'b'] <- "Excludes South Sudan"
product$Comments[product$Comments == 'c'] <- "Covers mainland Tanzania only"
product$Comments[product$Comments == 'd'] <- "Data are for the area controlled by the government of the Republic of Cyprus"
product$Comments[product$Comments == 'e'] <- "Excludes Abkhazia and South Ossetia"
product$Comments[product$Comments == 'f'] <- "Excludes Transnistria"
product[product$Comments != "",] # View valid comment column entries after edits

## Convert GDP type to numeric
product$GDP.Millions.of.US.Dollars <- gsub(",","", product$GDP.Millions.of.US.Dollars, fixed = TRUE) # Prep GDP column for
product$GDP.Millions.of.US.Dollars <- gsub(".","", product$GDP.Millions.of.US.Dollars, fixed = TRUE) # type conversion
product$GDP.Millions.of.US.Dollars <- as.numeric(product$GDP.Millions.of.US.Dollars) # Convert GDP type to numeric

## Convert Country.Rank type to integer
product$Country.Rank <- as.integer(product$Country.Rank)

## Output number of NA or empty values for each variable used in analysis
# sum(product$Country.Code == "")
# sum(is.na(product$Country.Rank))
# sum(product$Economy == "")
# sum(is.na(product$GDP.Millions.of.US.Dollars))
# sum(product$Comments == "")

product[!complete.cases(product),] # View all rows for which not all variable data is available

## Remove missing Country.Code values from the data frame
# product <- product[complete.cases(product),]
# str(product)
product1 <- subset(product, product$Country.Code != "")
# product1 <- subset(product1, !is.na(product1$GDP.Millions.of.US.Dollars))

## Extract only Country.Code and GDP column data to be merged
GDPdata <- product1[,c(1,2,4)]
str(GDPdata) # Review extracted data internal structure details
nrow(GDPdata[!complete.cases(GDPdata$Country.Code),]) # Confirm there are no missing Country.Code values in the data

GDPdata <- GDPdata[order(GDPdata$Country.Code),] # Order the data by Country.Code instead of GDP

# write.csv(GDPdata, "Product_clean.csv", row.names = FALSE)

```

```{r}
##############################
## Chris Boomhower
## MSDS 6306
## Unit 6 Case Study
## 06/11/2016
##############################

## Load required packages
# require(downloader)
# require(ggplot2)
# require(tidyr)
# require(dplyr)

## Verify current working directory
# getwd()
# setwd("Analysis//Data")
# getwd()

## Download data
educURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv"
download(educURL, destfile = "Education.csv")

list.files() # Confirm download to working directory

## Import Educational data and review raw data
EducRaw <- read.csv("Education.csv", stringsAsFactors = FALSE, header = TRUE) # Try reading characters in as strings instead of factors for easier manipulation
str(EducRaw) # Review raw data internal structure details
head(EducRaw) # Review beginning rows to ensure no blank observations
tail(EducRaw) # Review ending rows to ensure no blank observations

## Rename CountryCode variable to match GDPdata's Country.Code
Education <- rename(EducRaw, Country.Code = CountryCode)

## Check NAs or missing values in columns of interest
nrow(Education[Education$Country.Code == "",])
nrow(Education[Education$Income.Group == "",])
nrow(Education[Education$Short.Name == "",])
# nrow(EducRaw)

## Remove missing Income.Group values and assign subset to new data frame
# Education <- subset(EducRaw, EducRaw$Income.Group != "")

## Extract CountryCode and Income.Group columns
# Income <- Education[,1:3]
Income <- Education[,c(1,3,31)]
head(Income)

nrow(Income[Income$Country.Code == "",]) # Confirm there are no missing Country.Code values in the data
# write.csv(Income, "Income_clean.csv", row.names = FALSE)

```

```{r}
##############################
## Chris Boomhower
## MSDS 6306
## Unit 6 Case Study
## 06/11/2016
##############################

## Load required packages
# require(ggplot2)
# require(knitr)

## QUESTION 1: MATCH THE DATA BASED ON THE COUNTRY SHORTCODE. HOW MANY OF THE IDs MATCH?
## Merge Income and GDPdata
MergeData <- merge(Income, GDPdata, by = "Country.Code", all = TRUE)
str(MergeData) # Review raw data internal structure details
head(MergeData) # Review beginning rows to ensure no blank observations

## Indicate how many of the IDs match
length(intersect(GDPdata$Country.Code, Income$Country.Code))

## Indicate how many of the rows contain NAs
sum(!complete.cases(MergeData))

## Remove rows with missing data
MergeData1 <- MergeData[complete.cases(MergeData),]
nrow(MergeData1) # Provide row count after removing rows with missing data

## QUESTION 2: SORT THE DATA FRAME IN ASCENDING ORDER BY GDP (SO UNITED STATES IS LAST). WHAT IS THE 13TH COUNTRY IN THE RESULTING DATA FRAME?
MergeData1 <- MergeData1[order(MergeData1$GDP.Millions.of.US.Dollars, decreasing = FALSE),] # Sort the data frame by GDP
MergeData1$Short.Name[13] # Display only the 13th country in the data frame

## QUESTION 3: WHAT ARE THE AVERAGE GDP RANKINGS FOR THE "High income: OECD" AND "High income: nonOECD" GROUPS?
mean(subset(MergeData1, Income.Group == "High income: OECD")$Country.Rank)
mean(subset(MergeData1, Income.Group == "High income: nonOECD")$Country.Rank)

## QUESTION 4: PLOT THE GDP FOR ALL OF THE COUNTRIES. USE GGPLOT2 TO COLOR YOUR PLOT BY Income.Group
# MergeData1$Country.Code <- as.factor(MergeData1$Country.Code) # Convert Country.Code type to factor in order to reorder ggplot x-axis by Income.Group
# MergeData1$Country.Code <- factor(MergeData1$Country.Code, levels = MergeData1$Country.Code[order(MergeData1$GDP.Millions.of.US.Dollars)]) # Reorder Country.Code by Income.Group

ggplot(data = MergeData1, aes(x=Income.Group, y=GDP.Millions.of.US.Dollars, fill=Income.Group)) +
    geom_boxplot() +                                                                            # Create boxplots
    theme(axis.text.x = element_text(angle = 55, hjust = 1, size = 10)) +                       # Adjust X axis label size and position
    xlab("Income Group") + ylab("GDP (Millions of US Dollars)") + ggtitle("GDP for All Countries by Income Group") # Provide labels

ggplot(data = MergeData1, aes(x=Income.Group, y=log(GDP.Millions.of.US.Dollars), fill=Income.Group)) + # Re-plot log transformed GDP
    geom_boxplot() + stat_summary(fun.y=mean, geom="point", shape=23, size=3, fill="red") +     
    geom_jitter(shape=16, position=position_jitter(0.3)) +                                      # Add individual data points with jitter
    theme(axis.text.x = element_text(angle = 55, hjust = 1, size = 10)) +                       
    xlab("Income Group") + ylab("Log Transformed GDP (Millions of US Dollars)") + ggtitle("Log Transformed GDP for All Countries by Income Group") # Provide labels

## QUESTION 5: CUT THE GDP RANKING INTO 5 SEPARATE QUANTILE GROUPS. MAKE A TABLE VERSUS Income.Group. HOW MANY COUNTRIES ARE
## LOWER MIDDLE INCOME BUT AMONG THE 38 NATIONS WITH THE HIGHEST GDP?

## Create additional data frame and add quantile column
MergeData2 <- MergeData1
MergeData2$GDP.Quantile <- ntile(MergeData2$Country.Rank, 5) # Add 5 quantiles by Country.Rank to new GDP.Quantile column

## Generate table output
kable(MergeData2[,c(2:3,6)], format = "markdown", caption = "Country GDP Quantiles vs. Country GDP Rank:", align = 'l', row.names = FALSE)

## Count number of lower middle income countries
sum(MergeData2[(nrow(MergeData2)-37):nrow(MergeData2),]$Income.Group == "Lower middle income")

```